name: Treo Discord Tu Dong
on:
  workflow_dispatch: 
  schedule:
    # Nhớ sửa lại giờ cho đúng ca nhé
    - cron: '0 17 * * *' 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - env:
          TOKEN: ${{ secrets.TOKEN }}
        # Lệnh mới: Ép nó tải thư viện (npm install) trước, xong mới chạy code
        run: npm install && node index.js
